---
- name: Set up DHCP server
  hosts: DHCP-Server
  become: yes
  vars:
    dhcp_server_package: isc-dhcp-server
    dhcp_service: isc-dhcp-server
    dhcp_service_config: /etc/default/isc-dhcp-server
    dhcp_server_config: /etc/dhcp/dhcpd.conf
    dhcp6_server_config: /etc/dhcp/dhcpd6.conf
    configure_apparmor: false
    subnet: 192.168.100.0
    netmask: 255.255.255.0
    range_start: 192.168.100.140
    range_end: 192.168.100.149
    router: 192.168.100.254
    dns_servers:
      - 8.8.8.8
      - 1.1.1.1
  roles:
    - role: ansible-role-dhcp-server
