---
- name: Create a file on the Windows machine
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Ensure the directory exists
      win_file:
        path: P:/awxtower/ansible-playbooks/
        state: directory

    - name: Create a file at the specified location
      win_copy:
        content: "This is a sample file created by Ansible."
        dest: P:/awxtower/ansible-playbooks/sample-file.txt
