---
- name: Konfiguration vom TFTP-Server auf Switch anwenden
  hosts: switches
  gather_facts: no
  become: yes
  become_method: enable
  vars:
    tftp_server: "192.168.1.10"
    config_file: "switch_config.txt"

  tasks:
    - name: "Konfigurationsmodus: 'file prompt quiet' aktivieren"
      ios_config:  # <-- Änderung: ios_config statt ios_command
        lines:
          - file prompt quiet
        match: exact  # Stellt sicher, dass die Konfiguration nur einmal angewendet wird

    - name: Konfiguration vom TFTP-Server übernehmen
      ios_command:
        commands:
          - copy tftp://{{ tftp_server }}/{{ config_file }} running-config
      register: copy_result

    - name: Ergebnis anzeigen
      debug:
        var: copy_result
