---
- name: Konfiguration vom TFTP-Server auf Switch anwenden
  hosts: Switch01
  gather_facts: no
  become: yes
  become_method: enable
  vars:
    tftp_server: "192.168.100.132"
    config_file: "backups/switch_show_run_Switch01_20250303.txt"

  tasks:
    - name: "Konfigurationsmodus: 'file prompt quiet' aktivieren"
      ios_config:
        lines:
          - file prompt quiet
        match: exact

    - name: Konfiguration vom TFTP-Server übernehmen
      ios_command:
        commands:
          - copy tftp://{{ tftp_server }}/{{ config_file }} running-config
      register: copy_result
      # Ignoriere Fehler, wenn die Ausgabe "bytes copied" enthält
      failed_when: "'bytes copied' not in copy_result.stdout[0]"

    - name: Ergebnis anzeigen
      debug:
        var: copy_result
