---
- name: NTP-Server konfigurieren
  hosts: switches
  gather_facts: no
  connection: network_cli

  tasks:
    - name: NTP-Server konfigurieren
      ios_config:
        lines:
          - ntp server 0.de.pool.ntp.org prefer
          - ntp server 1.de.pool.ntp.org
        save_when: modified
