- name: Cisco Router Configuration
  hosts: routers
  gather_facts: no
  connection: network_cli
  tasks:
   - name: "Get current domain name"
      ios_command:
        commands:
          - "show running-config | include ip domain-name"
      register: current_domain_name

#    - name: "Set domain name"
#      ios_config:
#        lines:
#          - "ip domain-name 8.8.8.8"

    - name: "Set domain name if not configured"
      ios_config:
        lines:
          - "ip domain-name 8.8.8.8"
      when: "'ip domain-name 8.8.8.8' not in current_domain_name.stdout"
