- name: Cisco Router Configuration
  hosts: routers
  gather_facts: no
  connection: network_cli
  tasks:
    - name: "Set hostname"
      ios_config:
        lines:
          - "Router01"

    - name: "Disable DNS lookup"
      ios_config:
        lines:
          - "no ip domain-lookup"

    - name: "Set enable secret"
      ios_config:
        lines:
          - "enable secret cisco"



    - name: "Get current domain name"
      ios_command:
        commands:
          - "show running-config | include ip domain-name"
      register: current_domain_name

    - name: "Set domain name if not configured"
      ios_config:
        lines:
          - "ip domain-name 8.8.8.8"
      when: "'ip domain-name 8.8.8.8' not in current_domain_name.stdout"



    - name: "Check if user is already configured"
      ios_command:
        commands:
          - "show running-config | include username admin"
      register: current_user

    - name: "Create user with password if not configured"
      ios_config:
        lines:
          - "username admin secret cisco"
      when: "'username admin secret cisco' not in current_user.stdout"



    - name: "Enable service password encryption"
      ios_config:
        lines:
          - "service password-encryption"



    - name: "Check if RSA key pair is already generated"
      ios_command:
        commands:
          - "show running-config | include crypto key generate rsa"
      register: current_rsa_key

    - name: "Generate RSA key pair if not configured"
      ios_config:
        lines:
          - "crypto key generate rsa general-keys modulus 1024"
      when: "'crypto key generate rsa general-keys modulus 1024' not in current_rsa_key.stdout"



    - name: "Set SSH version to 2"
      ios_config:
        lines:
          - "ip ssh version 2"

    - name: "Configure console line"
      ios_config:
        lines:
          - "line con 0"
          - "password cisco"
          - "login local"
          - "exec-timeout 15 0"
          - "exit"

    - name: "Configure VTY lines"
      ios_config:
        lines:
          - "line vty 0 4"
          - "password cisco"
          - "login local"
          - "exec-timeout 15 0"
          - "transport input ssh"
          - "exit"

    - name: "Configure auxiliary line"
      ios_config:
        lines:
          - "line aux 0"
          - "password cisco"
          - "exec-timeout 15 0"
          - "login local"
          - "exit"
