---
- name: Backup Cisco Switch Configuration to TFTP
  hosts: Switch01
  gather_facts: yes
  vars:
    tftp_server: "192.168.100.132"
    tftp_root_path: "/var/tftpboot"  # Stellen Sie sicher, dass dieser Pfad korrekt ist
    config_filename: "backups/switch_show_run_{{ inventory_hostname }}_{{ timestamp }}.txt"
  tasks:
    - name: Generate a timestamp (nur Datum)
      set_fact:
        timestamp: "{{ '%Y%m%d' | strftime }}"

    - name: Debug: Zeige zu löschenden Pfad
      ansible.builtin.debug:
        var: "{{ tftp_root_path }}/{{ config_filename | regex_replace(timestamp, '.*') }}*.txt"

    - name: Lösche ALLE Backups für diesen Switch auf dem TFTP-Server
      ansible.builtin.shell:
        cmd: "find {{ tftp_root_path }} -type f -name 'switch_show_run_{{ inventory_hostname|lower }}_*.txt' -delete"
      delegate_to: "{{ tftp_server }}"
      become: yes
      ignore_errors: yes
      when: inventory_hostname|lower == "switch01"

    - name: Backup der Running-Config zum TFTP-Server
      cisco.ios.ios_command:
        commands:
          - command: "copy running-config tftp://{{ tftp_server }}/{{ config_filename }}"
            prompt:
              - "Address or name of remote host"
              - "Destination filename"
            answer:
              - "\n"
              - "\n"
        wait_for:
          - "result[0].stdout contains 'bytes copied in'"
      register: backup_result
      timeout: 60

    - name: Ergebnis anzeigen
      ansible.builtin.debug:
        var: backup_result
