---
- name: Backup Cisco Switch Configuration to TFTP
  hosts: Switch01
  gather_facts: no

  vars:
    tftp_server: "192.168.100.132"
    config_filename: "backups/switch_show_run.txt"

  tasks:
    - name: Backup der Running-Config zum TFTP-Server
      cisco.ios.ios_command:
        commands:
          - command: "copy running-config tftp://{{ tftp_server }}/{{ config_filename }}"
            prompt:
              - "Address or name of remote host"  # Prompt for TFTP server
              - "Destination filename"  # Prompt for filename
              - "Write file"  # Confirmation prompt
            answer:
              - "\n"  # Confirm TFTP server (press Enter)
              - "\n"  # Accept default filename (press Enter)
              - "\n"  # Confirm write (press Enter)
        wait_for:
          - "result[0] contains 'OK' or 'successful'"  # Adjust based on actual output
      register: backup_result
      timeout: 60  # Increase timeout to 60 seconds

    - name: Ergebnis anzeigen
      ansible.builtin.debug:
        var: backup_result
