---
- name: Backup Cisco Switch Configuration to TFTP
  hosts: Switch01
  gather_facts: yes
  vars:
    tftp_server: "192.168.100.132"
    tftp_root_path: "/var/tftpboot"
    ssh_user: "your_ssh_username"       # <--- AKTUALISIEREN!
    ssh_key_file: "/path/to/private_key # <--- AKTUALISIEREN! (optional)
    config_filename: "backups/switch_show_run_{{ inventory_hostname }}_{{ timestamp }}.txt"
  tasks:
    - name: Generate timestamp
      set_fact:
        timestamp: "{{ '%Y%m%d' | strftime }}"

    - name: Set deletion pattern
      set_fact:
        delete_pattern: "{{ tftp_root_path }}/backups/switch_show_run_{{ inventory_hostname | lower }}_*.txt"

    - name: Delete old backups on TFTP Server
      ansible.builtin.shell:
        cmd: "rm -f {{ delete_pattern }}"
      delegate_to: "{{ tftp_server }}"
      become: yes
      become_user: root
      vars:
        ansible_user: "{{ ssh_user }}"
        ansible_become: yes
        ansible_ssh_private_key_file: "{{ ssh_key_file | default('') }}"
        ansible_password: "{{ tftp_server_password | default('') }}"  # Nur wenn Passwort erforderlich
      ignore_errors: yes

    - name: Backup Running Config to TFTP
      cisco.ios.ios_command:
        commands:
          - command: "copy running-config tftp://{{ tftp_server }}/{{ config_filename }}"
            prompt:
              - "Address or name of remote host"
              - "Destination filename"
            answer:
              - "\n"
              - "\n"
        wait_for:
          - "result[0].stdout contains 'bytes copied in'"
      register: backup_result
      timeout: 60

    - name: Show result
      ansible.builtin.debug:
        var: backup_result
