---
- name: Backup Cisco Switch Configuration to TFTP
  hosts: Switch01
  gather_facts: yes
  vars:
    tftp_server: "192.168.100.132"
    tftp_root_path: "/var/tftpboot"  # Adjust to your TFTP root path
    config_filename: "backups/switch_show_run_{{ inventory_hostname }}_{{ timestamp }}.txt"
  tasks:
    - name: Generate timestamp (YYYYMMDD)
      set_fact:
        timestamp: "{{ '%Y%m%d' | strftime }}"

    - name: Set deletion pattern for old backups
      set_fact:
        delete_pattern: "{{ tftp_root_path }}/backups/switch_show_run_{{ inventory_hostname | lower }}_*.txt"

    - name: Delete existing backups for this switch
      ansible.builtin.shell:
        cmd: "rm -f {{ delete_pattern }}"
      delegate_to: "{{ tftp_server }}"
      become: yes
      ignore_errors: yes
      when: inventory_hostname | lower == "switch01"

    - name: Backup running config to TFTP
      cisco.ios.ios_command:
        commands:
          - command: "copy running-config tftp://{{ tftp_server }}/{{ config_filename }}"
            prompt:
              - "Address or name of remote host"
              - "Destination filename"
            answer:
              - "\n"
              - "\n"
        wait_for:
          - "result[0].stdout contains 'bytes copied in'"
      register: backup_result
      timeout: 60

    - name: Show backup result
      ansible.builtin.debug:
        var: backup_result
