---
- name: Speichern der Running-Config eines Cisco-Geräts in eine Textdatei und Push zu Git
  hosts: Switch01
  gather_facts: no
  tasks:

    - name: Ausführen des "show running-config"-Befehls
      ios_command:
        commands:
          - show running-config
      register: running_config_output

    - name: Speichern der Ausgabe in eine lokale Datei auf Windows
      delegate_to: localhost
      copy:
        content: "{{ running_config_output.stdout[0] }}"
        dest: "P:/awxtower/ansible-playbooks/running-config.txt"
      become: no  # Prevent any use of sudo on Windows

    - name: Git Add - Stage the file
      delegate_to: localhost
      command:
        cmd: "git add running-config.txt"
      args:
        chdir: "P:/awxtower/ansible-playbooks"
      become: no  # No sudo needed

    - name: Git Commit - Commit the changes
      delegate_to: localhost
      command:
        cmd: "git commit -m 'Updated running-config'"
      args:
        chdir: "P:/awxtower/ansible-playbooks"
      become: no  # No sudo needed

    - name: Git Push - Push to the remote repository
      delegate_to: localhost
      command:
        cmd: "git push origin main"  # Adjust 'main' if your branch is different
      args:
        chdir: "P:/awxtower/ansible-playbooks"
      become: no  # No sudo needed
