---
- name: Execute "show run" and commit to Git repository
  hosts: Switch01
  gather_facts: no
  tasks:

    - name: Run "show running-config" on the switch
      ansible.netcommon.cli_command:
        command: show running-config
      register: running_config_output

    - name: Save running-config to a file on the local computer
      delegate_to: localhost
      copy:
        content: "{{ running_config_output.stdout }}"
        dest: P:\\awxtower\ansible-playbooks\running-config.txt  # Update this path as needed
      become: no

    - name: Change to the Git repository directory on the local computer
      delegate_to: localhost
      ansible.builtin.command:
        cmd: git add running-config.txt
        chdir: P:\\awxtower\ansible-playbooks\  # Update this path to your Git repository
      register: git_add
      ignore_errors: yes
      become: no

    - name: Commit the new config to the Git repository
      delegate_to: localhost
      ansible.builtin.command:
        cmd: git commit -m "Updated running config for {{ inventory_hostname }} on {{ ansible_date_time.date }}"
        chdir: P:\\awxtower\ansible-playbooks\  # Update this path to your Git repository
      when: git_add is succeeded
      become: no

    - name: Push changes to the remote repository
      delegate_to: localhost
      ansible.builtin.command:
        cmd: git push origin main
        chdir: P:\\awxtower\ansible-playbooks\  # Update this path to your Git repository
      ignore_errors: yes
      become: no
