---
- name: Banner Config
  hosts: switches
  gather_facts: no
  collections: cisco.ios

  tasks:
    - name: Configure login banner
      cisco.ios.ios_banner:
        banner: login
        text: |
          Banner konfiguriert
          am 12.12.2024 um 11:58 Uhr
        state: present
