---
- name: Konfiguration des Cisco Switches
  hosts: switches
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Domain Lookup deaktivieren
      command: no ip domain-lookup

    - name: Enable Secret konfigurieren
      command: enable secret cisco

    - name: Konsolen-Login konfigurieren
      command: line con 0
      register: console_config

    - name: Konsolen-Passwort setzen
      command: password cisco
      when: console_config.rc == 0

    - name: Konsolen-Login aktivieren
      command: login
      when: console_config.rc == 0

    - name: Exec-Timer konfigurieren
      command: exec-timeout 15 0
      when: console_config.rc == 0

    - name: Hostname konfigurieren
      command: hostname Switch01

    - name: Domain-Name konfigurieren
      command: ip domain-name 8.8.8.8

    - name: Benutzer konfigurieren
      command: username admin secret cisco

    - name: Passwörter verschlüsseln
      command: service password-encryption

    - name: RSA-Schlüssel für SSH generieren
      command: crypto key generate rsa general-keys modulus 2048
      register: crypto_key_output

    - name: SSH Version 2 aktivieren
      command: ip ssh version 2

    - name: VTY-Leitungen konfigurieren
      command: line vty 0 4
      register: vty_config

    - name: VTY-Passwort setzen
      command: password cisco
      when: vty_config.rc == 0

    - name: VTY-Login aktivieren
      command: login local
      when: vty_config.rc == 0

    - name: Exec-Timer für VTY konfigurieren
      command: exec-timeout 15 0
      when: vty_config.rc == 0

    - name: Transport für VTY aktivieren
      command: transport input ssh
      when: vty_config.rc == 0
