---
- name: Banner Config
  hosts: Switch01
  gather_facts: no
  collections: cisco.ios

  tasks:
    - name: Configure login banner
      cisco.ios.ios_banner:
        banner: login
        text: |
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        state: present
