---
- name: Banner Config
  hosts: switches
  gather_facts: no
  collections: cisco.ios

  tasks:
    - name: Configure login banner
      cisco.ios.ios_banner:
        banner: login
        text: |
          #########################################
          #                                       #
          #                BANNER                 #
          #                                       #
          #########################################
        state: present
