---
- name: Switch-Konfiguration
  hosts: switches
  gather_facts: no
  tasks:
    - name: Verbindung mit dem Switch herstellen und die Running Config sichern
      cisco.ios.ios_config:
        backup: yes

    - name: Hostname des Switches setzen
      cisco.ios.ios_config:
        lines:
          - hostname {{ switch_hostname }}

