---

- name: Banner Config
  hosts: switches
  gather_facts: no
  tasks:
    - name: Bannerung
      ios_command:
      commands:
      banner: login
      text: |
        this is my login banner
        that contains a multiline
        string
      state: present
