---
- name: Konfiguration des Cisco Switches
  hosts: switches
  gather_facts: no
  connection: network_cli
  collections:
    - cisco.ios
  tasks:
    - name: Domain Lookup deaktivieren
      cisco.ios.ios_config:
        lines:
          - no ip domain-lookup

    - name: Enable Secret konfigurieren
      cisco.ios.ios_config:
        lines:
          - enable secret cisco

    - name: Konsolen-Login konfigurieren
      cisco.ios.ios_config:
        lines:
          - line con 0
          - password cisco
          - login
          - exec-timeout 15 0
        parents: line con 0

    - name: Hostname konfigurieren
      cisco.ios.ios_config:
        lines:
          - hostname Switch01

    - name: Domain-Name konfigurieren
      cisco.ios.ios_config:
        lines:
          - ip domain-name 8.8.8.8

    - name: Benutzer konfigurieren
      cisco.ios.ios_config:
        lines:
          - username admin secret cisco

    - name: Passwörter verschlüsseln
      cisco.ios.ios_config:
        lines:
          - service password-encryption

    - name: RSA-Schlüssel für SSH generieren
      cisco.ios.ios_config:
        lines:
          - crypto key generate rsa general-keys modulus 2048
      register: crypto_key_output

    - name: SSH Version 2 aktivieren
      cisco.ios.ios_config:
        lines:
          - ip ssh version 2

    - name: VTY-Leitungen konfigurieren
      cisco.ios.ios_config:
        lines:
          - line vty 0 4
          - password cisco
          - login local
          - exec-timeout 15 0
          - transport input ssh
        parents: line vty 5 15
