---
- name: Configure Banner on Switch
  hosts: switches
  gather_facts: no
  vars:
    banner_message: |
      *********************************************************
      *                                                       *
      *  UNAUTHORIZED ACCESS TO THIS DEVICE IS PROHIBITED     *
      *  All activities on this device are logged and         *
      *  monitored.                                           *
      *                                                       *
      *********************************************************
  tasks:
    - name: Configure banner
      ios_config:
        lines:
          - "{{ banner_message }}"
        parents: banner motd
      when: ansible_network_os == 'ios'

    - name: Save configuration
      ios_config:
        save: yes
      when: ansible_network_os == 'ios'
