---
- name: Speichern der Running-Config eines Cisco-Geräts in eine Textdatei
  hosts: Switch01
  gather_facts: no
  tasks:

    - name: Ausführen des "show running-config"-Befehls
      ios_command:
        commands:
          - show running-config
      register: running_config_output
 
    - name: Speichern der Ausgabe in eine lokale Datei
      local_action:
        module: copy
        content: "{{ running_config_output.stdout[0] }}"
        dest: "./running-configs/{{ inventory_hostname }}_running-config.txt"

 
