---
- name: Führe ip int brief aus
  hosts: switches
  gather_facts: false
  connection: network_cli

  tasks:
    - name: show run
      ios_command:
        commands:
          - show run
      register: config

    - name: Ensure the directory exists on the control node
      file:
        path: "/home/controlnode/show-output"
        state: directory
        mode: '0755'

    - name: Save output to local directory
      copy:
        content: "{{ config.stdout | replace('\\n', '\n') }}"
        dest: "/home/controlnode/show-output/{{ inventory_hostname }}.ios"


#   - name: save output to local directory
#      copy:
#        content: "{{ config.stdout | replace('\\n', '\n') }}" dest: "show-output/{{ inventory_hostname }}.ios"


#  tasks:
#    - name: Führe "ip int brief" aus
#      command: ip -o addr show
#      register: ip_output  # Speichert die Ausgabe des Befehls

#    - name: Zeige das Ergebnis des Befehls
#      debug:
#        var: ip_output.stdout
