---
- name: Save show run output to a file
  hosts: network_devices
  gather_facts: no
  tasks:
    - name: Execute show run command
      cisco.ios.ios_command:
        commands:
          - show run
      register: show_run_output

    - name: Save show run output to a file
      copy:
        content: "{{ show_run_output.stdout[0] }}"
        dest: "/path/to/save/show_run_output.txt"
      delegate_to: localhost
