---
- name: Führe ip int brief aus
  hosts: switches
  gather_facts: false

  tasks:
    - name: show run
         ios_command:
           commands:
           - show run
         register: config

   - name: save output to local directory
      copy:
        content: "{{ config.stdout | replace('\\n', '\n') }}" dest: "show-output/{{ inventory_hostname }}.ios"


#  tasks:
#    - name: Führe "ip int brief" aus
#      command: ip -o addr show
#      register: ip_output  # Speichert die Ausgabe des Befehls

#    - name: Zeige das Ergebnis des Befehls
#      debug:
#        var: ip_output.stdout
