---
- name: Führe ip int brief aus
  hosts: your_hosts_group
  gather_facts: false  # Falls du keine zusätzlichen Fakten sammeln möchtest

  tasks:
    - name: show run
         ios_command:
           commands:
           - show run
           - show ip route
           - show ip eigrp neighbors
           - show version
         register: config

   - name: save output to local directory
      copy:
        content: "{{ config.stdout | replace('\\n', '\n') }}" dest: "show-output/{{ inventory_hostname }}.ios"


#  tasks:
#    - name: Führe "ip int brief" aus
#      command: ip -o addr show
#      register: ip_output  # Speichert die Ausgabe des Befehls

#    - name: Zeige das Ergebnis des Befehls
#      debug:
#        var: ip_output.stdout
