---
- name: Speichern der Running-Config eines Cisco-Geräts in eine Textdatei
  hosts: Switch01
  gather_facts: no
  tasks:

    - name: Ausführen des "show running-config"-Befehls
      ios_command:
        commands:
          - show running-config
      register: running_config_output
 
    - name: Speichern der Ausgabe in eine lokale Datei
      delegate_to: localhost
      become: yes
      become_method: sudo
      vars:
        ansible_become_pass: "kali"
      copy:
        content: "{{ running_config_output.stdout[0] }}"
        dest: "/home/controlnode/sh_run_config.txt"

 
