---
- name: VLANs mit IPs erstellen
  hosts: switches
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Erstelle VLAN 10
      ios_config:
        parents:
          - vlan 10
        lines:
          - name VLAN10

    - name: Konfiguriere VLAN 10 Schnittstelle
      ios_config:
        lines:
          - interface vlan 10
          - ip address 192.168.10.1 255.255.255.0
          - no shutdown

    - name: Erstelle VLAN 20
      ios_config:
        parents:
          - vlan 20
        lines:
          - name VLAN20

    - name: Konfiguriere VLAN 20 Schnittstelle
      ios_config:
        lines:
          - interface vlan 20
          - ip address 192.168.20.1 255.255.255.0
          - no shutdown

    - name: Erstelle VLAN 30
      ios_config:
        parents:
          - vlan 30
        lines:
          - name VLAN30

    - name: Konfiguriere VLAN 30 Schnittstelle
      ios_config:
        lines:
          - interface vlan 30
          - ip address 192.168.30.1 255.255.255.0
          - no shutdown

    - name: Zuweisen der VLANs auf das Interface
      ios_config:
        lines:
          - interface gi1/0/5
          - switchport mode trunk
          - switchport trunk allowed vlan 10, 20, 30
          - shutdown
