---
- name: VLANs auf einem Cisco-Switch erstellen
  hosts: cisco_switch
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Erstelle VLAN 10
      ios_command:
        commands:
          - vlan 10
          - name VLAN10
      register: result_vlans

    - name: Erstelle VLAN 20
      ios_command:
        commands:
          - vlan 20
          - name VLAN20
      register: result_vlans

    - name: Erstelle VLAN 30
      ios_command:
        commands:
          - vlan 30
          - name VLAN30
      register: result_vlans

    - name: Zeige VLAN-Erstellung an
      debug:
        msg: "{{ result_vlans }}"
