---
- name: VLANs erstellen
  hosts: cisco_switch
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Erstelle VLAN 10
      ios_vlan:
        vlan_id: 10
        name: "VLAN10"
        state: present
      register: vlan_10

    - name: Erstelle VLAN 20
      ios_vlan:
        vlan_id: 20
        name: "VLAN20"
        state: present
      register: vlan_20

    - name: Erstelle VLAN 30
      ios_vlan:
        vlan_id: 30
        name: "VLAN30"
        state: present
      register: vlan_30
