---
- name: VLANs erstellen
  hosts: switches
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Erstelle VLAN 10
      ios_command:
        commands:
          - vlan 10
          - name VLAN10

    - name: Erstelle VLAN 20
      ios_command:
        commands:
          - vlan 20
          - name VLAN20

    - name: Erstelle VLAN 30
      ios_command:
        commands:
          - vlan 30
          - name VLAN30
